import { Component,OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ApiService } from '../../core/api.service';
import { Employee,OrganizationUnit,Position } from '../../core/models';
@Component({selector:'app-employees',standalone:true,imports:[CommonModule,FormsModule],template:`
<section class="page"><div class="page-heading"><div><span class="eyebrow">Núcleo de gestión</span><h1>Personal</h1><p>Registro y consulta de trabajadores.</p></div><button class="primary" type="button" (click)="showForm=!showForm">{{showForm?'Cerrar':'+ Nuevo trabajador'}}</button></div>
<div class="panel" *ngIf="showForm"><h2>Nuevo trabajador</h2><form class="form-grid" (ngSubmit)="save()">
<label>Código<input name="employeeCode" [(ngModel)]="form.employeeCode" required></label><label>DNI<input name="documentNumber" [(ngModel)]="form.documentNumber" required></label><label>Nombres<input name="firstName" [(ngModel)]="form.firstName" required></label><label>Apellidos<input name="lastName" [(ngModel)]="form.lastName" required></label><label>Correo<input type="email" name="email" [(ngModel)]="form.email" required></label><label>Teléfono<input name="phone" [(ngModel)]="form.phone"></label><label>Fecha ingreso<input type="date" name="hireDate" [(ngModel)]="form.hireDate" required></label>
<label>Área<select name="organizationUnitId" [(ngModel)]="form.organizationUnitId"><option value="">Sin asignar</option><option *ngFor="let unit of units" [value]="unit.id">{{unit.name}}</option></select></label>
<label>Cargo<select name="positionId" [(ngModel)]="form.positionId"><option value="">Sin asignar</option><option *ngFor="let position of positions" [value]="position.id">{{position.name}}</option></select></label>
<div class="form-actions"><button class="primary" type="submit">Guardar trabajador</button></div></form></div>
<div class="toolbar"><input placeholder="Buscar por DNI, código o nombre..." [(ngModel)]="search" (keyup.enter)="load()"><button type="button" (click)="load()">Buscar</button></div>
<div class="table-card"><table><thead><tr><th>Código</th><th>Trabajador</th><th>DNI</th><th>Correo</th><th>Ingreso</th><th>Estado</th></tr></thead><tbody><tr *ngFor="let e of employees"><td>{{e.employeeCode}}</td><td><strong>{{e.lastName}}, {{e.firstName}}</strong></td><td>{{e.documentNumber}}</td><td>{{e.email}}</td><td>{{e.hireDate}}</td><td><span class="badge">{{e.status}}</span></td></tr></tbody></table><div class="empty-state" *ngIf="!employees.length">No hay trabajadores registrados.</div></div></section>`})
export class EmployeesComponent implements OnInit{employees:Employee[]=[];units:OrganizationUnit[]=[];positions:Position[]=[];search='';showForm=false;form=this.emptyForm();constructor(private readonly api:ApiService){}ngOnInit():void{this.load();this.api.units().subscribe(v=>this.units=v);this.api.positions().subscribe(v=>this.positions=v);}load():void{this.api.employees(this.search).subscribe(v=>this.employees=v);}save():void{const payload={...this.form,organizationUnitId:this.form.organizationUnitId||null,positionId:this.form.positionId||null,managerEmployeeId:null};this.api.createEmployee(payload).subscribe(()=>{this.form=this.emptyForm();this.showForm=false;this.load();});}private emptyForm(){return{employeeCode:'',documentNumber:'',firstName:'',lastName:'',email:'',phone:'',hireDate:new Date().toISOString().slice(0,10),organizationUnitId:'',positionId:''};}}